name: "Publish"
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jameshenry/publish-shell-action@v1
        with:
          github-token: ${{ github.token }}
